const ActionTypes = {
  SET_BOOKS: 'SET_BOOKS',
  SELECTED_BOOK: 'SELECTED_BOOK',
  REMOVE_SELECTED_BOOK: 'REMOVE_SELECTED_BOOK',
  COUNT_CURRENT_PAGE: 'COUNT_CURRENT_PAGE',
};

export default ActionTypes;
